# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CardReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardReader
  pod 'PayCardsRecognizer'

  target 'CardReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
